### ISSUE TITLE
Language selection on upload page losing key in URL

### ISSUE THREAD

**Issue by betrisey** [notifyme-app/notifyme-webpages#1]
Hello,

I've tried the app and it's great, I've just found a small issue.

When visiting the upload page (e.g. https://upload.notify-me.ch/?v=2#CAIS2AIKY...) and clicking the FR or EN link, the user gets redirected to the page without the key in the URL (https://upload.notify-me.ch/fr/) resulting in an error when trying to submit.

I'm not familiar with Hugo so I don't know the best way to fix it, maybe changing the links on page load to add the key here: https://github.com/notifyme-app/notifyme-webpages/blob/b06933ee7b0acc12a49e592696dc6839a0d38d91/assets/js/uploadpageIndex.js#L76

Also it may also be better to include the user's language in the generated QR code:
https://github.com/notifyme-app/notifyme-webpages/blob/b06933ee7b0acc12a49e592696dc6839a0d38d91/assets/js/qrgenerator/qrgenerator.js#L103

**Comment by martinalig** [comment]
Hi, thanks for the input. We will look into this!
